=== aditee-c/xml/BookXmlSchemaProject/src/Books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.zensar.com/Books"
	xmlns:zen="http://www.zensar.com/Books" elementFormDefault="qualified">
	<element name="book-Info">
		<complexType>
			<sequence>
				<element name="book" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="book-id">
								<simpleType>
									<restriction base="int">
										<minInclusive value="1001"></minInclusive>
										<maxInclusive value="9999"></maxInclusive>
										<totalDigits value="4"></totalDigits>
									</restriction>
								</simpleType>
							</element>
							<element name="title">
								<simpleType>
									<restriction base="string">
									<minLength value="5"/>
									<maxLength value="50"/>
									</restriction>
								</simpleType>
							</element>
							<element name="author" type="string" maxOccurs="unbounded"/>
							<element name="price" type="float" minOccurs="0"/>
							<element name="publish-date" type="date"/>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== aditee-c/xml/BookXmlSchemaProject/bin/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<zen:book-Info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:zen="http://www.zensar.com/Books" xsi:schemaLocation="http://www.zensar.com/Books Books.xsd ">
  <zen:book>
    <zen:book-id>1235</zen:book-id>
    <zen:title>Harry Potter : Sorcerer's Stone</zen:title>
    <zen:author>J K Rowling</zen:author>
    <zen:publish-date>1997-01-01</zen:publish-date>
  	  
  </zen:book>
  <zen:book>
  <zen:book-id>1236</zen:book-id>
    <zen:title>Harry Potter : The Chamber of Secrets</zen:title>
    <zen:author>J K Rowling</zen:author>
    <zen:publish-date>1998-01-01</zen:publish-date>
  </zen:book>
  <zen:book>
  <zen:book-id>1237</zen:book-id>
    <zen:title>Harry Potter : The prisioner of Azkaban</zen:title>
    <zen:author>J K Rowling</zen:author>
    <zen:publish-date>1999-01-01</zen:publish-date>
  </zen:book>
  <zen:book>
  <zen:book-id>1238</zen:book-id>
    <zen:title>Harry Potter : The Goblet of Fire</zen:title>
    <zen:author>J K Rowling</zen:author>
    <zen:publish-date>2000-01-01</zen:publish-date>
  </zen:book>
  <zen:book>
  <zen:book-id>1239</zen:book-id>
    <zen:title>Harry Potter : The Order of Phoenix</zen:title>
    <zen:author>J K Rowling</zen:author>
    <zen:publish-date>2003-01-01</zen:publish-date>
  </zen:book>
  <zen:book>
  <zen:book-id>1240</zen:book-id>
    <zen:title>Harry Potter : The Half Blod Prince</zen:title>
    <zen:author>J K Rowling</zen:author>
    <zen:publish-date>2005-01-01</zen:publish-date>
  </zen:book>
  <zen:book>
  <zen:book-id>1241</zen:book-id>
    <zen:title>Harry Potter : The Deathly Hollows part1</zen:title>
    <zen:author>J K Rowling</zen:author>
    <zen:publish-date>2007-01-01</zen:publish-date>
  	</zen:book>
  	<zen:book><zen:book-id>1242</zen:book-id>
    <zen:title>Harry Potter : The Deathly Hollows part2</zen:title>
    <zen:author>J K Rowling</zen:author>
    <zen:publish-date>2011-01-01</zen:publish-date>
  	</zen:book>
</zen:book-Info>
